import { useState, useCallback } from "react";
import Icon from "@/components/ui/icon";

type Format = "clash" | "clash-meta" | "surge";

const FORMAT_OPTIONS: { value: Format; label: string; icon: string }[] = [
  { value: "clash", label: "Clash", icon: "Layers" },
  { value: "clash-meta", label: "Clash Meta", icon: "Layers" },
  { value: "surge", label: "Surge", icon: "Zap" },
];

const SAMPLE_INPUT =
  "vless://a1b2c3d4-e5f6-7890-abcd-ef1234567890@nl-01.vpnservice.io:443?encryption=none&security=tls&sni=nl-01.vpnservice.io&type=tcp#NL-01-Amsterdam";

function generateMockOutput(input: string, format: Format): string {
  const isVless = input.trim().toLowerCase().startsWith("vless://");
  const isVmess = input.trim().toLowerCase().startsWith("vmess://");
  const proto = isVless ? "vless" : isVmess ? "vmess" : "vless";

  if (format === "surge") {
    return `[Proxy]
NL-01-Amsterdam = ${proto}, nl-01.vpnservice.io, 443, username=a1b2c3d4-e5f6-7890-abcd-ef1234567890, tls=true, sni=nl-01.vpnservice.io

[Proxy Group]
Proxy = select, NL-01-Amsterdam, DIRECT

[Rule]
GEOIP,private,DIRECT
FINAL,Proxy`;
  }

  const isMeta = format === "clash-meta";

  return `# Generated by VPN Dashboard
# Format: ${isMeta ? "Clash Meta (Mihomo)" : "Clash Premium"}

port: 7890
socks-port: 7891
allow-lan: false
mode: rule
log-level: info

proxies:
  - name: "NL-01-Amsterdam"
    type: ${proto}
    server: nl-01.vpnservice.io
    port: 443
    uuid: a1b2c3d4-e5f6-7890-abcd-ef1234567890
    network: tcp
    tls: true
    ${isMeta ? 'client-fingerprint: chrome\n    ' : ''}servername: nl-01.vpnservice.io
    skip-cert-verify: false

proxy-groups:
  - name: "Proxy"
    type: select
    proxies:
      - NL-01-Amsterdam
      - DIRECT

rules:
  - GEOIP,private,DIRECT,no-resolve
  - MATCH,Proxy`;
}

export default function ClashConverter() {
  const [input, setInput] = useState(SAMPLE_INPUT);
  const [format, setFormat] = useState<Format>("clash");
  const [output, setOutput] = useState("");
  const [copied, setCopied] = useState(false);
  const [converting, setConverting] = useState(false);

  const handleConvert = useCallback(() => {
    if (!input.trim()) return;
    setConverting(true);
    setCopied(false);
    setTimeout(() => {
      const result = generateMockOutput(input, format);
      setOutput(result);
      setConverting(false);
    }, 800);
  }, [input, format]);

  const handleCopy = useCallback(() => {
    if (!output) return;
    navigator.clipboard.writeText(output).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }, [output]);

  const handleDownload = useCallback(() => {
    if (!output) return;
    const ext = format === "surge" ? ".conf" : ".yaml";
    const mimeType = format === "surge" ? "text/plain" : "application/x-yaml";
    const blob = new Blob([output], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `config${ext}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [output, format]);

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="animate-fade-up" style={{ animationDelay: "0ms" }}>
        <h1 className="text-2xl font-bold text-foreground tracking-tight mb-1">
          Clash Converter
        </h1>
        <p className="text-sm text-gray-400">
          Конвертируйте VLESS/VMess ссылки в формат Clash, Clash Meta или Surge
        </p>
      </div>

      {/* Format selector */}
      <div
        className="animate-fade-up flex gap-2"
        style={{ animationDelay: "80ms" }}
      >
        {FORMAT_OPTIONS.map((opt) => (
          <button
            key={opt.value}
            onClick={() => {
              setFormat(opt.value);
              setOutput("");
              setCopied(false);
            }}
            className={`inline-flex items-center gap-2 px-4 py-2.5 text-sm font-medium rounded-xl transition-all ${
              format === opt.value
                ? "bg-v-500 text-white shadow-sm"
                : "bg-white text-gray-600 border border-v-100 hover:bg-v-50"
            }`}
          >
            <Icon name={opt.icon} size={15} />
            {opt.label}
          </button>
        ))}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Input */}
        <div
          className="animate-fade-up bg-white border border-v-100 rounded-2xl p-6 flex flex-col"
          style={{ animationDelay: "160ms" }}
        >
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-base font-semibold text-foreground">
              Входные данные
            </h2>
            <span className="text-xs text-gray-400">
              VLESS / VMess ссылка
            </span>
          </div>

          <textarea
            value={input}
            onChange={(e) => setInput(e.target.value)}
            rows={8}
            placeholder="vless://uuid@server:port?params#name"
            className="flex-1 w-full bg-gray-50 border border-gray-100 rounded-xl p-4 text-xs text-gray-700 font-mono resize-none focus:outline-none focus:ring-2 focus:ring-v-500/20 focus:border-v-500 transition-colors leading-relaxed"
          />

          <button
            onClick={handleConvert}
            disabled={converting || !input.trim()}
            className="w-full inline-flex items-center justify-center gap-2 bg-v-500 hover:bg-v-600 disabled:opacity-60 disabled:cursor-not-allowed text-white text-sm font-semibold px-5 py-3 rounded-xl transition-colors mt-4"
          >
            {converting ? (
              <>
                <Icon name="Loader2" size={16} className="animate-spin" />
                Конвертация...
              </>
            ) : (
              <>
                <Icon name="ArrowRightLeft" size={16} />
                Конвертировать
              </>
            )}
          </button>
        </div>

        {/* Output */}
        <div
          className="animate-fade-up bg-white border border-v-100 rounded-2xl p-6 flex flex-col"
          style={{ animationDelay: "240ms" }}
        >
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-base font-semibold text-foreground">
              Результат
            </h2>
            {output && (
              <div className="flex items-center gap-2">
                <button
                  onClick={handleCopy}
                  className={`inline-flex items-center gap-1.5 text-sm font-medium px-3 py-1.5 rounded-lg transition-colors ${
                    copied
                      ? "bg-v-50 text-v-500"
                      : "bg-gray-50 hover:bg-gray-100 text-gray-600"
                  }`}
                >
                  <Icon name={copied ? "Check" : "Copy"} size={14} />
                  {copied ? "Скопировано" : "Скопировать"}
                </button>
                <button
                  onClick={handleDownload}
                  className="inline-flex items-center gap-1.5 text-sm font-medium bg-v-50 hover:bg-v-100 text-v-500 px-3 py-1.5 rounded-lg transition-colors"
                >
                  <Icon name="Download" size={14} />
                  Скачать {format === "surge" ? ".conf" : ".yaml"}
                </button>
              </div>
            )}
          </div>

          {output ? (
            <pre className="flex-1 bg-gray-50 border border-gray-100 rounded-xl p-4 text-xs text-gray-700 font-mono overflow-auto leading-relaxed whitespace-pre max-h-[420px]">
              {output}
            </pre>
          ) : (
            <div className="flex-1 flex flex-col items-center justify-center text-center py-16">
              <div className="w-14 h-14 rounded-2xl bg-v-50 flex items-center justify-center mb-4">
                <Icon name="FileCode2" size={24} className="text-v-300" />
              </div>
              <p className="text-sm text-gray-400 max-w-[240px]">
                Вставьте ссылку и нажмите "Конвертировать" для получения конфига
              </p>
            </div>
          )}
        </div>
      </div>

      {/* Instructions */}
      <div
        className="animate-fade-up"
        style={{ animationDelay: "320ms" }}
      >
        <h2 className="text-lg font-semibold text-foreground mb-4">
          Инструкция
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {[
            {
              step: "1",
              title: "Вставьте ссылку",
              description:
                "Скопируйте вашу VLESS или VMess ссылку из панели управления ключами и вставьте в поле ввода.",
              icon: "ClipboardPaste",
            },
            {
              step: "2",
              title: "Выберите формат",
              description:
                "Укажите целевой формат: Clash для стандартного клиента, Clash Meta для Mihomo, Surge для iOS/macOS.",
              icon: "Settings2",
            },
            {
              step: "3",
              title: "Скачайте конфиг",
              description:
                "Скопируйте результат или скачайте файл. Импортируйте его в ваш клиент через настройки профилей.",
              icon: "Download",
            },
          ].map((item) => (
            <div
              key={item.step}
              className="bg-white border border-v-100 rounded-xl p-5 hover:shadow-md transition-all"
            >
              <div className="flex items-center gap-3 mb-3">
                <div className="w-8 h-8 rounded-lg bg-v-50 flex items-center justify-center">
                  <span className="text-sm font-bold text-v-500">
                    {item.step}
                  </span>
                </div>
                <span className="text-sm font-semibold text-foreground">
                  {item.title}
                </span>
              </div>
              <p className="text-sm text-gray-500 leading-relaxed">
                {item.description}
              </p>
            </div>
          ))}
        </div>
      </div>

      {/* Supported formats note */}
      <div
        className="animate-fade-up bg-v-50 border border-v-200 rounded-xl p-5"
        style={{ animationDelay: "400ms" }}
      >
        <div className="flex items-start gap-3">
          <div className="w-9 h-9 rounded-lg bg-v-100 flex items-center justify-center flex-shrink-0">
            <Icon name="Info" size={18} className="text-v-500" />
          </div>
          <div>
            <div className="text-sm font-semibold text-v-700 mb-1">
              Поддерживаемые форматы
            </div>
            <p className="text-sm text-v-600 leading-relaxed">
              Конвертер поддерживает ссылки VLESS и VMess. Для Trojan-ссылок
              используйте Xray Config Generator. Результат совместим с Clash
              Premium, Clash Meta (Mihomo), Clash for Android, Stash и Surge 5+.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
